version: "3"
services:  
  userapp:
    build: .\user-app
    container_name: "userapp-dockercompose"
    ports:
      - 8080:8080
    depends_on:
      - mongodb  
 
  wasteapp:
    build: .\waste-app
    container_name: "wasteapp-dockercompose"
    ports:
      - 8181:8181
    depends_on:
      - mongodb     
  
  mongodb:
    image: mongo:latest
    container_name: mongodb-dockercompose
    ports:
      - 27017:27017  